<?php

include("fpdf.php");
include('GFirestore.php');


//Salary
$data = new Firestore('Salary');
$result[] = $data->getAllDocuments();


//PDF Generator

class PDF extends FPDF
{
function Header()
{
    // Select Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(20);
    // Framed title
    $this->Cell(150,10,'Invoice for Period Ending '.date('F, Y')." "."(RM)",1,0,'C');
    // Line break
    $this->Ln(25);
}

function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'This is autogenerated and signature is not needed',0,0,'C');
}
}

$totalnett = 0;
$totaleis = 0;
$totaleis = 0;
$totalsocso = 0;
$totaltax = 0;
$i = 0;
foreach($result[0] as $row){
    $i++;

    $totalnett += $row["NettSalary"]; 
    $totaleis  += $row["MEIS"]; 
    $totalsocso  += $row["MSocso"];
    $totalepf  += $row["Mepf"];
    $totaltax  += $row["totalTaxEmployer"];

}


ob_start();
$pdf = new PDF();
$pdf->AddPage();
//Set Border Colour
$pdf->SetDrawColor(220 ,220,220);
$pdf->SetFont('Arial','',10);

//Employee Details
//Name
$pdf->Cell(38,6,"Total Salaries",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totalnett,2),1,0,'R');
// Line break
$pdf->Ln(7);

//EmployeeID
$pdf->Cell(38,6,"Total EIS",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totaleis,2) ,1,0,'R');
// Line break
$pdf->Ln(7);

//Bank
$pdf->Cell(38,6,"Total Socso",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totalsocso,),1,0,'R');
// Line break
$pdf->Ln(7);

//BankAccount  
$pdf->Cell(38,6,"Total EPF",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totalepf,2),1,0,'R');
// Line break
$pdf->Ln(10);

//Salary Details
//Basic Salary
$pdf->Cell(38,6,"Total Tax",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totaltax,2),1,0,'R');
// Line break
$pdf->Ln(7);

//Allowance
$pdf->Cell(38,6,'Total Salary Need to be paid',1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,number_format($totalnett,2),1,0,'R');
// Line break
$pdf->Ln(7);

// Line break
$pdf->Ln(7);

//Output PDF
$pdf->Output('D',"TotalInvoice".".pdf",'false');
ob_end_flush(); 


?>
